### ISSUE TITLE
Failing build if skipping optional step of TailwindCss

### ISSUE THREAD

**Issue by Marcosaurios** [storyblok/sveltekit-ultimate-tutorial-series#16]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

Hi! 
It's very nice to see an Svelte implementation for Storyblok! However the first tutorial has some drawbacks, let's have the first issue here :D

I've followed the 1st tutorial carefully and multiple times, and I found that the combination of:
- Installing latest svelte versions as suggested by the tutorial
- [And not installing the optional postcss section](https://www.storyblok.com/tp/add-a-headless-cms-to-svelte-in-5-minutes)

Leaves you in a failing build state.

**Solution?** I managed to somehow fix it installing `typescript@latest` and `svelte-preprocess@latest`, somehow these are required by svelte to understand typescript when using `storyblok/svelte` (and of course adding the preprocess function in the `svelte.config.js`). I'm not sure if this is the correct approach to fix it, but I find it unfair having to install TS to run a pure JS Svelte setup with Storyblok.

---

## Expected Behavior

`npm run dev` should occur successfully, without errors.

## Current Behavior

`npm run dev` outputs the following:
![Captura](https://user-images.githubusercontent.com/24393669/232254930-10098780-43b2-494f-8159-8716ea239d4e.JPG)

## Steps to Reproduce
You can check it yourself in [my fork on `main`](https://github.com/Marcosaurios/sveltekit-ultimate-tutorial-series) and the solution in [the `solution` branch](https://github.com/Marcosaurios/sveltekit-ultimate-tutorial-series/tree/solution)
Or follow the 1st tutorial steps, skipping the optional TailwindCSS part, these are:

1. `npm create svelte@latest sveltekit-ultimate-tutorial-series `
2. `cd sveltekit-ultimate-tutorial-series`
3. `npm install`
4. `npm i vite-plugin-mkcert -D`
5. `npm install @storyblok/svelte`

**Comment by josefineschaefer** [comment]
Thanks for raising this @Marcosaurios! We will check the issue you mentioned and get back to you. Thanks for your patience :)

**Comment by roberto-butti** [comment]
Hello @Marcosaurios ,
Exactly at the moment, you need to import as a dependency (and you can use them as DEV dependencies - so in the `devDependencies` section) both svelte-preprocess and typescript.

- `svelte-preprocess` is needed by the client side for rendering svelte files.
- `typescript` is needed by SvelteComponents.

I tried this solution with both scenario, with sophisticated CSS frameworks (that require stuff like postcss) and more basic CSS like Bulma (installed via CDN - so no additional requirements - )

I think that by performing in the future some fine-tuning in the SvelteComponents we can skip (in the future) the requirement for Typescript.

**Comment by roberto-butti** [comment]
Another way, if you want to avoid installing svelte-preprocess you can use vite-preprocess, just because is a dependency of SvelteKit so you don't have to install it.
If you want to explore more the differences between svelte-preprocess and vite-preprocess take a look here: https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/preprocess.md
I'm going to close this issue.
